version: 1.2
workflows:
- name: GraphEvaluation
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GraphEvaluation.wdl
  testParameterFiles:
- name: hapestry_validate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_validate.wdl
  testParameterFiles:
- name: hapestry_annotate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_annotate.wdl
  testParameterFiles:
- name: hapestry_annotate_scattered
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_annotate_scattered.wdl
  testParameterFiles:
- name: hapestry_merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_merge.wdl
  testParameterFiles:
- name: hapestry_merge_scattered
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/hapestry_merge_scattered.wdl
  testParameterFiles:
- name: multi_annotate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/multi_annotate.wdl
  testParameterFiles:
- name: bcftools_collapse
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/bcftools_collapse.wdl
  testParameterFiles:
- name: samtools_merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/samtools_merge.wdl
  testParameterFiles:
